/**
 * =================================================================
 * DATABASE TYPE DEFINITIONS
 * =================================================================
 * This file creates TYPE SAFETY between PostgreSQL and TypeScript
 *
 * WHY THIS EXISTS:
 * - Catches bugs at COMPILE TIME instead of runtime
 * - Autocomplete in your IDE for database queries
 * - Prevents typos in column names
 * - Documents the database schema in TypeScript land
 *
 * EXAMPLE OF BUG THIS PREVENTS:
 * // Without types:
 * const memory = await supabase.from('memories').select('conten')  // Typo!
 * // Fails at RUNTIME ❌
 *
 * // With types:
 * const memory = await supabase.from('memories').select('conten')
 * // TypeScript ERROR: Property 'conten' does not exist ✅
 */

// =================================================================
// BASE MEMORY TYPE
// =================================================================
// This represents a memory row EXACTLY as it exists in PostgreSQL

export interface Memory {
  // Identity
  id: string;  // UUID stored as string in TypeScript

  // Ownership
  user_id: string;  // UUID reference to auth.users

  // Content
  content: string;  // The actual memory text

  // Intelligence
  embedding: number[] | null;  // Vector represented as array
  // WHY nullable: Some memories might not have embeddings yet
  // Example: Just saved, embedding generation still processing

  // Context
  metadata: MemoryMetadata;  // Structured JSONB data

  // Timeline
  created_at: string;  // ISO 8601 timestamp string
  updated_at: string;  // ISO 8601 timestamp string
}

// =================================================================
// METADATA STRUCTURE
// =================================================================
// Type-safe structure for the JSONB metadata column
//
// WHY TYPED METADATA:
// - Prevents storing random garbage in metadata
// - IDE autocomplete for metadata properties
// - Documents what metadata fields mean

export interface MemoryMetadata {
  // System fields (added by triggers)
  created_by_trigger?: boolean;
  schema_version?: string;

  // Application fields
  tags?: string[];  // ["important", "work", "personal"]
  source?: MemorySource;  // Where did this memory come from?
  confidence?: number;  // 0-1: How confident is the agent?
  conversation_id?: string;  // Link to specific conversation
  agent_name?: string;  // Which agent created this?

  // Extensible: Add more fields as needed
  [key: string]: unknown;  // Allow additional properties
}

// =================================================================
// MEMORY SOURCE ENUM
// =================================================================
// Where did this memory originate?

export type MemorySource =
  | 'user_input'       // User explicitly told the agent
  | 'conversation'     // Inferred from conversation
  | 'web_scrape'       // Extracted from web content
  | 'api_import'       // Imported from external API
  | 'langraph_agent'   // Created by LangGraph node
  | 'manual_entry';    // Added via web UI

// =================================================================
// DATABASE OPERATION TYPES
// =================================================================
// Different "shapes" of memory for different database operations

/**
 * INSERT: What you provide when CREATING a memory
 * - id: Auto-generated by database (uuid_generate_v4)
 * - user_id: Set by application (from auth context)
 * - embedding: Optional (can be added later)
 * - metadata: Optional (defaults to {})
 * - timestamps: Auto-set by database
 */
export interface MemoryInsert {
  user_id: string;
  content: string;
  embedding?: number[];
  metadata?: Partial<MemoryMetadata>;
}

/**
 * UPDATE: What you can CHANGE in an existing memory
 * - All fields optional (update only what you want)
 * - id: Cannot be updated (primary key)
 * - user_id: Cannot be updated (security)
 * - timestamps: Auto-updated by trigger
 */
export interface MemoryUpdate {
  content?: string;
  embedding?: number[];
  metadata?: Partial<MemoryMetadata>;
}

// =================================================================
// SEARCH RESULT TYPES
// =================================================================
// Results from search functions have additional computed fields

/**
 * Result from match_memories() function
 * Includes everything from Memory PLUS similarity score
 */
export interface MemorySearchResult {
  id: string;
  user_id: string;
  content: string;
  metadata: MemoryMetadata;
  similarity: number;  // 0.0 to 1.0, added by search function
  created_at: string;
  // Note: embedding excluded for performance (large data)
}

/**
 * Result from get_recent_memories() function
 * Lightweight version with only essential fields
 */
export interface RecentMemory {
  id: string;
  content: string;
  metadata: MemoryMetadata;
  created_at: string;
}

// =================================================================
// SUPABASE CLIENT TYPE
// =================================================================
// This tells the Supabase client about our database schema
//
// WHY THIS IS POWERFUL:
// - Full type safety for ALL database queries
// - Autocomplete for table names, column names, RPC functions
// - Type inference for query results

export interface Database {
  public: {
    Tables: {
      memories: {
        Row: Memory;           // SELECT returns this
        Insert: MemoryInsert;  // INSERT expects this
        Update: MemoryUpdate;  // UPDATE expects this
      };
    };
    Functions: {
      // Semantic search
      match_memories: {
        Args: {
          query_embedding: number[];
          match_threshold?: number;
          match_count?: number;
          filter_user_id?: string;
        };
        Returns: MemorySearchResult[];
      };

      // Recent memories
      get_recent_memories: {
        Args: {
          limit_count?: number;
        };
        Returns: RecentMemory[];
      };

      // Memory count
      get_user_memory_count: {
        Args: Record<string, never>;  // No arguments
        Returns: number;
      };

      // Metadata search
      search_by_metadata: {
        Args: {
          metadata_query: MemoryMetadata;
          limit_count?: number;
        };
        Returns: RecentMemory[];
      };
    };
  };
}

// =================================================================
// UTILITY TYPES
// =================================================================
// Helper types for common operations

/**
 * Type guard: Check if object is a valid Memory
 */
export function isMemory(obj: unknown): obj is Memory {
  if (typeof obj !== 'object' || obj === null) return false;
  const m = obj as Partial<Memory>;
  return (
    typeof m.id === 'string' &&
    typeof m.user_id === 'string' &&
    typeof m.content === 'string' &&
    typeof m.created_at === 'string' &&
    typeof m.updated_at === 'string'
  );
}

/**
 * Type guard: Check if embedding has correct dimensions
 */
export function isValidEmbedding(embedding: unknown): embedding is number[] {
  return (
    Array.isArray(embedding) &&
    embedding.length === 1536 &&
    embedding.every(n => typeof n === 'number')
  );
}
